name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Встановлення залежностей
      - run: bun install

      # Збірка проекту
      - run: bunx vite build

      # Деплой на GitHub Pages
      - run: bunx gh-pages -d dist
