name: deploy
jobs:
  my-job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # Встановлення залежностей
      - run: bun install

      # Запуск Vite для розробки
      - run: bunx --bun vite

      # Збірка проекту
      - run: bunx --bun vite build
